[package]
name = "fontgrep"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
jwalk = "0.8.1"
rayon = "1.10.0"
read-fonts = "0.27.2"
skrifa = "0.28.1"
